### ISSUE TITLE
Série: komplexnější podpora

### ISSUE THREAD

**Issue by black23** [moravianlibrary/CPK#205]
Zobrazování a linkování sérií je skvělý začátek. Podle mého názoru by bylo užitečné přidat další podporu, která uživatelům zjednoduší práci:
- [x] podpora pro zobrazování a linkování sérií
- [x] hledání podle názvů sérií
- [x] zobrazení informace o sérii ve výsledku hledání
- [x] zobrazení informace o sérii v detailu titulu
- [ ] našeptávání při hledání názvů sérií
- [ ] seřazení série podle pořadí dílů, automaticky po kliknutí na její název

![Screenshot at Mar 20 11-24-02](https://user-images.githubusercontent.com/5516936/54677361-fee5c680-4b02-11e9-93d4-d33e85dc4c0f.png)

![Screenshot_2019-03-20 Výsledky vyhledávání - Harry Hole ](https://user-images.githubusercontent.com/5516936/54677349-f5f4f500-4b02-11e9-867f-64b3639fe897.png)

**Comment by xmorave2** [comment]
Řazení podle čísla série nebude implementováno. Do pokročilého vyhledávání bude přídana možnost hledat v názvech sérií
